### PR TITLE
Enforce long fingerprints in branches.yaml

### PR DESCRIPTION
**Pull request by krawthekrow**
This commit opts to enforce full length fingerprints in branches.yaml directly during validation, since it is generally good practice to use full-length fingerprints in configuration files anyway.

See #327.

---

Checklist:

 - [x] I have split up this change into one or more appropriately-delineated commits.
 - [x] The first line of each commit is of the form "[component]: do something"
 - [x] I have written a complete, multi-line commit message for each commit.
 - [x] I have formatted any Go code that I have changed with gofmt.
 - [x] I have signed each commit with my GPG key.
 - [x] My changes have passed CI.
 - [x] I have built my changes locally, and tested that the changes work as expected.
 - [x] I have deployed a cluster incorporating my changes, and checked that it deploys successfully.
 - [x] I have assigned this issue to an appropriate reviewer. (Choose @celskeggs if you are not otherwise certain.)
 - [x] I consider my PR complete and ready to be merged without my further input, assuming that it passes CI and code review.

### CODE REVIEW

**Comment by celskeggs** [comment]
@krawthekrow do you plan to test this on a cluster?

**Comment by krawthekrow** [comment]
I was planning to do that when it comes time to figure out autodeployment on Jenkins.

**Comment by celskeggs** [comment]
You'll need to rebase this. Sorry.

**Comment by celskeggs** [comment]
This appears to already have been merged through #339. So closing.

**Pull request closed without merging**
