### PR TITLE
Add build for ceph

### PR DESCRIPTION
**Pull request by celskeggs**
I'm putting this here for the sake of sanity-checking and helping explain things, rather than looking for a full code review.

Not that a full code review would be unwelcome.

### CODE REVIEW

**Comment by celskeggs** [comment]
Just to check, did you confirm the hash was correct from upstream?

**Comment by sdukhovni** [comment]
No, I didn't, sorry about that. I'll try to have that done tomorrow.

**Comment by sdukhovni** [comment]
Might be good to have some document somewhere detailing standards for code reviews, so it's easier for more contributors to get involved.

**Comment by celskeggs** [comment]
I'm temporarily closing this PR, since Ceph is getting pushed out. I'll re-open it once it's ready again.

**Pull request closed without merging**
