### PR TITLE
Create homeworld directory on spire populate if missing

### PR DESCRIPTION
**Pull request by ed1d1a8d**
Addresses https://github.com/sipb/homeworld/issues/138.

### CODE REVIEW

**Comment by celskeggs** [comment]
Have you tested these changes locally?

**Comment by ed1d1a8d** [comment]
I have not.

**Comment by celskeggs** [comment]
Besides testing:

 - You should probably squash these two commits, because the second one is pretty trivial.
 - You will also want to sign your commits with your GPG key, and generate a key if you don't have one.

**Comment by ed1d1a8d** [comment]
Changes tested locally.

**Pull request merged**
