### PR TITLE
Upgrade kubernetes to 1.9.2

### LINKED ISSUE #150: Upgrade kubernetes to 1.9.2
Upstream update checklist:

- [x] Ensure upstream version is latest.
- [x] Review changelogs for breaking changes.
- [x] Verify upstream release hash.
- [x] Add upgrade-kubernetes-1.9.2 branch with update.
- [x] Implement any repackaging changes.
- [x] Test cluster deployment with changes.
- [ ] Merge changes.

NOTE: Depends on #100.

### PR DESCRIPTION
**Pull request by celskeggs**
Fixes #150.

A more-straightforward-than-expected upgrade of the kubernetes version.

### CODE REVIEW

**Comment by celskeggs** [comment]
Woops, forgot to push that to the upstream repository. Here you go. (I assume you already know that you should be verifying against the kubernetes upstream as well, not just my copy of source.)

**Comment by celskeggs** [comment]
@krawthekrow: have you verified the hash?

**Comment by krawthekrow** [comment]
Yes, I have verified the hash against a freshly downloaded copy.

**Comment by celskeggs** [comment]
Just rebasing.

**Pull request merged**
