### PR TITLE
Fix spire setup supervisor-ssh crashing when run twice

### LINKED ISSUE #131: spire setup supervisor-ssh is not idempotent
Removing the `authorized_keys` file twice fails the second time.

### PR DESCRIPTION
**Pull request by krawthekrow**
Check that the file exists before mv-ing it. Fixes #131.

### CODE REVIEW

**Comment by celskeggs** [comment]
Merging this is blocked on getting #135 merged.

**Comment by celskeggs** [comment]
I accidentally published a different change as 0.1.21 -- I would renumber it, but it's not possible to rewrite a version in the repository once it's been published, so you'll need to renumber this to 0.1.22, and rebase it against the HEAD of `better-addon-deploy`.

Since there's a bit more review before #145 gets merged, and so the head of `better-addon-deploy` may change, you might want to wait until #145 has been merged, and then just rebase against master.

**Comment by ichung** [comment]
Is there a better way to handle debian version numbers?  It seems like we will have a recurring problem with them every time we have concurrent changes.

**Comment by celskeggs** [comment]
@ichung: I don't have a better solution. Any ideas?

**Comment by celskeggs** [comment]
Can you rebase this and renumber the version?

**Comment by celskeggs** [comment]
(Also, sometimes I don't get a notification when a commit is pushed, so when you've resolved things, it's usually fastest to assign this PR back to me, so that I can take a look quickly.)

**Comment by krawthekrow** [comment]
Oh, that's a good idea. (Also, I should stop relying on Zephyr as a reliable communication platform.)

**Comment by celskeggs** [comment]
Zephyr usually works fine, but has edge cases, especially when other conversations are happening.

**Pull request merged**
