### PR TITLE
bazel: pin bazel version in use

### LINKED ISSUE #378: Reproducibly select version of Bazel
Currently, we use the latest Bazel version in CI -- which means that sometimes master breaks because Bazel stopped supporting something one of our dependencies does.

It would be really nice to have builds that don't migrate from "working" to "broken" just because of an updated release getting published. We should find a way to install a particular version and bump it explicitly.

### PR DESCRIPTION
**Pull request by celskeggs**
Instead of using the latest available Bazel version in the upstream apt repo, pull down pinned Bazel versions from upstream GitHub, so that we can avoid having Bazel change out from under us.

Fixes #378.

---

Checklist:

 - [x] I have split up this change into one or more appropriately-delineated commits.
 - [x] The first line of each commit is of the form "[component]: do something"
 - [x] I have written a complete, multi-line commit message for each commit.
 - [x] I have formatted any Go code that I have changed with gofmt.
 - [x] I have signed each commit with my GPG key.
 - [x] My changes have passed CI.
 - [x] I have built my changes locally, and tested that the changes work as expected.
 - [ ] ~I have deployed a cluster incorporating my changes, and checked that it deploys successfully.~
 - [x] I have assigned this issue to an appropriate reviewer. (Choose @celskeggs if you are not otherwise certain.)
 - [x] I consider my PR complete and ready to be merged without my further input, assuming that it passes CI and code review.

### CODE REVIEW

**Comment by celskeggs** [comment]
Changes broke under Jenkins because curl wasn't installed outside of the build chroot. I've added curl to the package installation step.

**Comment by celskeggs** [comment]
@cryslith can you re-review? I've added changes to jenkins-build.sh that were necessary for this to work under Jenkins.

**Comment by cryslith** [comment]
Approved but I cannot press the button until I get home from workOn Sep 3, 2019 14:31, Cel Skeggs <notifications@github.com> wrote:@cryslith can you re-review? I've added changes to jenkins-build.sh that were necessary for this to work under Jenkins.

**Comment by celskeggs** [comment]
Thanks! I'll just merge the thing directly.

**Pull request merged**
