### PR TITLE
Upgrade flannel to 0.9.0

### PR DESCRIPTION
**Pull request by krawthekrow**
Once again, I don't see a revision number anywhere. If I understand correctly, the revision number for flannel appears to be referenced in two places in the repository, and the current value for the revision number is different in both references.

### CODE REVIEW

**Comment by celskeggs** [comment]
When you increment the version number, you should reset the revision number to 1. The revision is usually a counter of incremental changes to a downstream repackaging of upstream code, so we increment it when we make a local change and there's no new upstream release.

And yeah, the -2 in the flannel.yaml file is a mistake. It should be -3. Since you're changing the version, it makes sense for you to also change the revision.

**Comment by krawthekrow** [comment]
Changes to revisions included.

**Comment by celskeggs** [comment]
For the sake of posterity and reproducibility, can you describe the process you used to verify this upstream code?

Also, this system works better if you sign your own commits. Do you have a PGP key? I can also sign it for you with my key, but then lots of things look slightly weird, such as this PR appearing as "closed" instead of "merged".

You will also want to rebase this commit against the new master branch.

**Comment by celskeggs** [comment]
I can't reproduce the hash that you provided.

The steps I used were the following:

    $ wget https://github.com/coreos/flannel/archive/v0.9.0.tar.gz
    $ ungzip v0.9.0.tar.gz
    $ xz v0.9.0.tar
    $ sha512sum v0.9.0.tar.xz

Can you provide more precise instructions for what you did to get this hash?

**Comment by krawthekrow** [comment]
I did `tar -xzvf ` and then `tar -cJf`, which was quite silly in retrospect. I've updated both repositories so that the procedure used is the same as the one you described, except with `gzip -d v0.9.0.tar.gz` instead of `ungzip 0.9.0.tar.gz`. For reference, I'm using gzip version 1.6 and xz version 5.1.0a.

**Comment by celskeggs** [comment]
Did you actually update the hash in the file? It still appears to be incorrect still -- and I think the same one as before.

**Comment by celskeggs** [comment]
Can you rebase this?

**Comment by krawthekrow** [comment]
Rebased.

**Comment by celskeggs** [comment]
Please file a corresponding pull request on homeworld-upstream, making sure that it's rebased.

(Sorry for the delay -- I've been hosed.)

**Comment by krawthekrow** [comment]
Oops, sorry, I keep having the impression that I had already filed that PR. It should be filed now.

**Comment by krawthekrow** [comment]
Fixed. Sorry I didn't notice it earlier either.

**Comment by celskeggs** [comment]
I forgot to change my review back to "approved", but it's merged anyway.

**Pull request merged**
